name: Feature branch
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    name: Unit and integration tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: gradle test --rerun-tasks
